# Site
name: 'Dr. Suess'
description: 'Many Thoughts, Few Voices'
logo: 'assets/images/avatar1.jpg'
favicon: 'assets/images/favicon.ico'
# host: '127.0.0.1'
baseurl: ''
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
# permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    kyle:
      name: kyle
      site: https://kylesuess.com
      avatar: /assets/images/avatar1.jpg
      bio: "Lots of nebulous thoughts. Sometimes adventuring, other times being a potato. A fondness for animals. // INTP + Capricorn"
      instagram: https://www.instagram.com/drsu3ss/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kyle
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 8



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [Gemfile, Gemfile.lock, docker-compose.yml, README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
