# Site
name: 'MySite'
description: 'Coming Soon'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
host: 'https://drsuess.github.io'
baseurl: ''
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    me:
      name:           
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi"
      email:          
      twitter:        

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [Gemfile, Gemfile.lock, docker-compose.yml, README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
